experiment_name: "fairness_face_recognition"

datasets:
  - bfw

models:
  - arcface
  - facenet512
  - ghostfacenet
  - mobilefacenet
  - sface

demographic_attribute: gender

run_improvement_stage: false